// Generated by https://quicktype.io

export interface JSONData {
    myteams: MyTeam[];
    teams: Team[];
}

export interface MyTeam {
    _id:         string;
    code:        string;
    name:        string;
    games:     Game[];
}

export interface Team {
    code: string;
    name: string;
    image:string;
}

export interface Game {
    gameCode: string,
    date: Date,
    goalsFavor: number,
    goalsAgainst: number,
    rivalCode:string,
    local: boolean
}

export interface ComponentPropsFavoriteTeams {
    myTeams: MyTeam[];
    teams: Team[];
    getData:Function;
    
}

export interface ComponentPropsGameDetail {
    myTeamName:string;
    myTeamImage:string ;
    rivalName:string;
    rivalImage:string;
    gameData:Game;
    myTeamCode:string; 
    setLoEnabled:Function;
    getData:Function;
    
}

export interface ComponentPropsNewGame {
    setLoEnabled:Function;
    getData:Function;
    teams:Team[];
}

export interface ComponentPropsTeamCalendar {
    myTeams:MyTeam[];
    teams:Team[];
    setLoEnabled:Function;
    getData:Function;
}

export interface ComponentPropsTeam {
    name:string;
    image:string;
}
