// Generated by https://quicktype.io

export interface JSONData {
    myteams: MyTeam[];
    teams: Team[];
}

export interface MyTeam {
    _id:         string;
    code:        string;
    name:        string;
    games:     Game[];
}

export interface Team {
    code: string;
    name: string;
    image:string;
}

export interface Game {
    gameCode: string,
    date: Date,
    goalsFavor: number,
    goalsAgainst: number,
    rivalCode:string,
    local: boolean
}

export interface ComponentProps {
    myTeams:MyTeam[];
    teams: Team[];
}